# Generated by Django 3.0.7 on 2020-07-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pertanyaan', models.CharField(max_length=255)),
                ('jawaban', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'chatbot_dataset',
            },
        ),
        migrations.CreateModel(
            name='Kamus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('synonym1', models.CharField(max_length=255)),
                ('synonym2', models.CharField(blank=True, max_length=255)),
                ('synonym3', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'chatbot_kamus',
            },
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.CharField(max_length=255)),
                ('output', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'chatbot_query',
            },
        ),
    ]
